### ISSUE TITLE
monky-status hangs forever on large repositories

### ISSUE THREAD

**Issue by michaelklishin** [ananthakumaran/monky#35]
With a repository like [rabbitmq-server](http://hg.rabbitmq.com/rabbitmq-server/), `monky-status` seems to block forever until interrupted.

Magit can handle repositories as large or even larger (like the entire Emacs git mirror) just fine.

**Comment by Bounga** [comment]
This issue is old. Is it still relevant @michaelklishin ?

**Comment by Wilfred** [comment]
FWIW I have tried monky on some very large repos without issues.

**Comment by Bounga** [comment]
@Wilfred Ok I'll close this issue. If it happens again to someone we'll open a new one.
