### ISSUE TITLE
Monky reports "default repository not configured" when pushing to a repository

### ISSUE THREAD

**Issue by tddsg** [ananthakumaran/monky#52]
Hi,

When pushing my commits to a repository, by using the shortcut key `P`, 
I always encounter the error message like below:

```
Running hg push --branch my-branch-name 
Hg exited abnormally with code 255.
default repository not configured!
```

It happens to me in both my machines at work and at home.
I have tried to configure the file `.hg/hgrc` with both `default` and `default-push`
but it doesn't work.

Can anyone advise how can I resolve this issue?

Thank you and in advance!

**Comment by Bounga** [comment]
@tddsg Thanks a lot for the fix. It's merged now.
